### ISSUE TITLE
Question: HACS: custom repositories

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#10]
Hi,
you don't know why it can't be created custom repositories through HACS?

![HACS](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/f27a3dfd-434e-40b5-b8de-15da5f4dd259)

**Comment by PatrikTrestik** [comment]
Yes, this is on my work list for January.
My repo is missing few parts to be compatible with HACS.

**Comment by PatrikTrestik** [comment]
Repo is now compatible with HACS. Please test.

**Comment by matomatusov** [comment]
HI,
thank you for the info.
Description in the picture.

![HACS description](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/a28b100a-e740-45e5-885e-b0bf83ecee5f)

**Comment by PatrikTrestik** [comment]
I have to finish HACS registration. 
I hope that this is last piece missing.

@matomatusov was it possible to install repo through HACS?

**Comment by matomatusov** [comment]
Hi,
what is repo?

**Comment by PatrikTrestik** [comment]
> Hi, what is repo?

Sorry :) >> custom repository
