### ISSUE TITLE
Unfortunately, integration cannot establish a connection to the wallbox

### ISSUE THREAD

**Issue by AlexBlack8439** [PatrikTrestik/homeassistant-solax-http#12]
Hello,
Unfortunately, integration cannot establish a connection to the wallbox.
IP address and SN as password are correct.
However, no device is displayed. X3-EV22K
Thank you Greetings Alex

**Comment by PatrikTrestik** [comment]
@AlexBlack8439 please let me know how was issue solved.
And also let me know if some instructions are not  clear, it will help others.
Thanks.
