### ISSUE TITLE
Custom Password support

### ISSUE THREAD

**Issue by Schafy** [PatrikTrestik/homeassistant-solax-http#14]
I changed the password of the web interface (since the serial is broadcasted in the open SSID). Afterwards I no longer receive data. Would it be possible to have an API password independent from the serial?

**Comment by PatrikTrestik** [comment]
Hi, it is already possible. Fill your password to SN field. I use it only as password (90% sure).

In next version I'll charge label of field to be more descriptive.

**Comment by Schafy** [comment]
Are there any requirements in length and complexity regarding the password? I used a generated password including special characters.

**Comment by PatrikTrestik** [comment]
Do you experience some errors?
I think that if you can access local web, password works.

**Comment by Schafy** [comment]
I fooled a bit around. Alphanumerical password with 20 digits is not working while password including special characters but only 10 digits (like the serial) is working fine.
Local web access via browser is working with every kind of password. Maybe some protection mechanism in the api preserving code injections?

**Comment by Philipp-X1** [comment]
Just for info: the Password Setting is documented here:
[https://www.solaxcloud.com/wifiSetting/index.html](url)

![IMG_2452](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/146736973/3b20230b-3f0e-4b74-8427-d18be8bc83db)
