### ISSUE TITLE
Serial number of inverter or wallbox is needed?

### ISSUE THREAD

**Issue by tomchovanec** [PatrikTrestik/homeassistant-solax-http#15]
Hi, cloud you please explicitly describe, which serial number is required? SN of the Inverted or the wallbox? Is not clear actually so I don't know if is possible to use WB without inverter (this should be mentioned too in readme). Thank you for you work!!!

**Comment by fretarts** [comment]
It's actually not the serial number but the registration  No. from the wifi of the EV charger. The number next to the QR code that you used to setup the wifi.

**Comment by tomchovanec** [comment]
Thanks, that makes sense. I think that the same inconsistency is for inverter and CloudApi. The SN is required for cloud, bude the ReqNo is required. It took me a hour to figure out that the SN is not the SN, but ReqNo. 🤦‍♂️

**Comment by PatrikTrestik** [comment]
Hi, you are right, it is confusing.
In fact it is "api password" which is by default equal to registration number, but can be changed. 

I'll fix labeling in next version.

**Comment by fretarts** [comment]
BTW thanks for your great work Patrik! It really help me a lot debugging my installation. 

Like many others I had to use the API as the modbus connection is already used to connect to the inverter (in my case via 2 waveshare adapters).

**Comment by tomchovanec** [comment]
> BTW thanks for your great work Patrik! It really help me a lot debugging my installation.
> 
> Like many others I had to use the API as the modbus connection is already used to connect to the inverter (in my case via 2 waveshare adapters).

I think that modbus could work... it can be connected in parallel. I cannot test it yet. In theory, 9600 baud speed should be used instad of 19200 for inverter. But I cannot test it to be sure right now. Only WB-energyMeter connection won't work for sure, because in this case wb is modbus client and energy meter works as server.

**Comment by fretarts** [comment]
You are right it can work in parallel... but than you are limited to the data requested by the inverter which is pretty much limited to the current charger power (modbus is a single master protocol). 

The waveshare RS485 to Eth has also the option to copy the modbus data to multiple host but same limitations as above. The API however give you quite some comprehensive data about almost everything.
