### ISSUE TITLE
unclear how to setup

### ISSUE THREAD

**Issue by moonraker69** [PatrikTrestik/homeassistant-solax-http#16]
Great that somebody took care to integrate the Solax EV charger. I have installed this as custom repository and looks good, system restarted, etc. but I never did get any pop ups nor configuratin button to configure IP address of the charger or my serial. So how is this setup supposed to work. Also dont see any installation instructions here as readme.
Can you help ?
BR
moonraker69

**Comment by PatrikTrestik** [comment]
If you have HACS it should be visible as new integration.
Just add integration and select SolaX HTTP API.

There is and will not be autodetection as for example with switches. It is technically complicated.

**Comment by moonraker69** [comment]
ok finally I got it working, my fault was that I didnt actually install the integration after download, I was really confused that I didnt find an appropriate name for it something like solax ev charger or even solax http, would have been clear and I stopped after adding repository and adding integration. Today I noticed that there was a new integration available which was called solax inverter local API. I didnt know that this is the right one to install. After installing this it just worked out of the box. any hints how to integrate it best into your energy card on dashboard e.g. to get similar view what is available in solax cloud ?

**Comment by Philipp-X1** [comment]
Did you take a look at this: https://github.com/flixlix/power-flow-card-plus
?

**Comment by michinbg** [comment]
Unfortunately I have problems with the installation.

I proceeded as follows:
1) download into HACS
2) open integration
3) click on "homeassistant-solax-http"
4) open HACS repository on my HA
5) Go to Devices and Services
6) add integration
7) Select solax inverter local API
8) I display the IP address of my **### inverter** in the popup
9) I enter the SN of my ### **inverter** as a password, 10 characters!!
10) unfortunately I always get an error message, no devices or entities

If I enter the IP address of the inverter in the browser I can log in with the serial number

what am I doing wrong?

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/99540117/cc37b1f2-c441-4d2f-8018-df5f28c0aa76)

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/99540117/dd065fd7-f820-4aab-832f-6733a8120315)


![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/99540117/e496a102-cbd7-4d6d-b436-5f7387102e3f)

This error originated from a custom integration.

Logger: custom_components.solax_http.plugin_solax_ev_charger
Source: custom_components/solax_http/plugin_solax_ev_charger.py:1017
integration: SolaX Inverter Local API (documentation, issues)
First occurred: 6:33:15 PM (2 occurrences)
Last logged: 6:38:25 PM

unrecognized inverter type - serial number : unknown

**Comment by Philipp-X1** [comment]
You are writing about Inverter? This Repository only works with EV-Charger.

**Comment by michinbg** [comment]
thanks, I swapped the IP address. now with EV charger it works.
THANKS

**Comment by PatrikTrestik** [comment]
I noticed that there is still wrong title in integration manifest which is misleading.

Closing this with raising more clear Bug https://github.com/PatrikTrestik/homeassistant-solax-http/issues/20.
