### ISSUE TITLE
Integration of SolaX Wallbox X3-EVC-11.0-(PXH)

### ISSUE THREAD

**Issue by edli83** [PatrikTrestik/homeassistant-solax-http#17]
Hi Patrik,
I tried to install my Wallbox with your integration - but it failed.
Firmware of my wall box is the last one - Ver. 1.12 with WiFi 3.007.04.
Wallbox is connected via Modbus to my X3 Hyb Gen4 inverter, also integrated in HA via WiFi. Also the inverter has the latest firmware.

I try to add a new Hub within Wills SolaX Integration - see picture:
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/e83382c9-5e48-4d52-abd2-578cfd0c2d77)

Then put in the IP-adress (fake adress here ...):
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/dd005eb9-94b7-4f04-b02d-890efd9e9e63)

A new Hub is now stored - but without connection:
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/e4c82e33-6776-4edf-9ce1-023778a722dc)

Also the installed entities seams not to be the right ones:
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/188a050f-8bf6-42b9-9e02-ce9ccdb619f6)

I found a description where I should get a request for IP-adress and HTTP API password - but this don´t come:
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/ea160e6a-3f7c-49ea-8767-e11866aa096d)

The integration afterwards should have this picture:
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/71a3b515-2eaf-4b28-b257-3fb8ebba6c9a)

Where is my mistake?
Hopefully you could help with a tipp.

Thank you in advance

**Comment by edli83** [comment]
Ultra fast response - thank you

I understand - I added now the integration and put in my Wallbox Data - but unfortunately I get no entities:
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149812865/0c1b4b92-5569-4fb2-8feb-2a141464f3ad)

I already have changed the password for the WiFi connetction to the wallbox - but this should hopefully not be the issue.
Or do the integration not accept "$; @; !; %) for password?

Stefan

**Comment by edli83** [comment]
Or is there a limitat of 10 characters?

**Comment by Philipp-X1** [comment]
Yes there is a limit of 10 characters.
Did you manage to setup it up yet?

**Comment by edli83** [comment]
Hi,
yes, I assume this and tried a shorter password.
So Integration works good.
Thank you very much for this integration - very good job.
