### ISSUE TITLE
Entities not viewable

### ISSUE THREAD

**Issue by lieglw** [PatrikTrestik/homeassistant-solax-http#2]
Hi Patrik, thank you for your work. Just have a question regarding the entities. Some of them are not available. Is this because of the satus of the EV Charger.
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/149818606/4e88255f-d252-49fd-bc3a-730b4b3a2fa3)
E.g Power is not available but Current.
Would the htpp version for the inverters also possible?
Thank You
Wolfgang

**Comment by johny-mnemonic** [comment]
And there even is an existing integration using the WiFi dongle connection instead of Modbus RTU.

**Comment by lieglw** [comment]
Thanks will test it. 
@PatrikTrestik How can I make the entities visible/ usable

Have test switching the modes (Eco, Stop, etc) works very good and a very fast response time.

**Comment by PatrikTrestik** [comment]
> Thanks will test it. @PatrikTrestik How can I make the entities visible/ usable
> 
> Have test switching the modes (Eco, Stop, etc) works very good and a very fast response time.

Standard HA, go to entities list and enable what you want .

**Comment by lieglw** [comment]
Sorry, new to HA. Works all very good. Thank You.
Issue is closed in my opinion.
