### ISSUE TITLE
Issue with API

### ISSUE THREAD

**Issue by Gazzyoung** [PatrikTrestik/homeassistant-solax-http#28]
Hello,

I have downloaded the integration and added my Solax API details from Solax cloud and added my internal IP address of my charger however it does not find any entities.

Thanks in advance

**Comment by Gazzyoung** [comment]
I get this from my API url with the inverter SN in - {
    "success": false,
    "exception": "Query success!",
    "result": "no auth!",
    "code": 0
}

**Comment by PatrikTrestik** [comment]
I see it was solved in discussion on thread of Modbus integration.
Closing. Feel free to comment if you still have errors.
