### ISSUE TITLE
Battery to EV Charger

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#33]
Hi,
If I switch Battery to EV Charger to Enabled, it goes back to Disabled.
You don't know what the problem could be?

![1](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/050eae5b-469d-4de0-90b4-b134ef200480)

**Comment by PatrikTrestik** [comment]
Connection between Charger and Inverter does not work. Let your installer check RS485 wiring.

**Comment by matomatusov** [comment]
The green mode of the Charge works for me.
I assume the connection is OK.
The connection of the inverter and the charger I think should be correct. Modbus set to EV with braud rate 9600 and only two wires leading to the charger.

Thanks

**Comment by matomatusov** [comment]
Same thing inverter

**Comment by PatrikTrestik** [comment]
One other idea. You have either:
* tested it when Inverter was in StandBy mode.
* your Inverter modbus is locked.

Have you tested same setting through SolaxClaud?

**Comment by matomatusov** [comment]
Hi,

- Inverter is Normal mode

- I think the modbus inverter is unlocked.

![1](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/533baf95-1f75-4aae-bc5a-5db8ad61aeee)

- [ ] Have you tested same setting through SolaxClaud?

Is it meant through the SolaX app?
There it works in the advanced settings.

**Comment by PatrikTrestik** [comment]
Thank it is most probably bug in SolaX modbus integration. Please start bug there and I'll check.

**Comment by matomatusov** [comment]
Hi, 
Question about the wallbox charge added entity.
Couldn't it be reset after 24:00 hours?
Similar to SolaX Today's Solar Energy.

Thanks

**Comment by PatrikTrestik** [comment]
As per my knowledge, it is reset after each Charge. Internal feature of SolaX.

**Comment by matomatusov** [comment]
and wouldn't it be possible to treat it somehow in HA so that the reset is after 24:00?

Thanks with information.

**Comment by PatrikTrestik** [comment]
> and wouldn't it be possible to treat it somehow in HA so that the reset is after 24:00?
> 
> Thanks with information.

Unfortunately not. Changer resets number on every Stop. If you need it you have to do some "derivative" and "integral" HA sensor math. Might be possible, but I'm not sure.

But nearly same value can be calculated with Rieman integral HA sensor derived from Charging Power. Its accuracy will depend on how often you read values, but it should give you usable number per day.
