### ISSUE TITLE
Wrong Charge Phase mapping for sw ver 1.13

### ISSUE THREAD

**Issue by josefburger** [PatrikTrestik/homeassistant-solax-http#36]
Hello, I have a problem with registr mapping, in my opinion you are using the wrong registr number. You are using  0x625, but it is now 0x63B. 

`case 0x625:
return [{"reg":70,"val":f"{payload}"}]`

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/6623611/92de8ae6-244e-438f-8beb-2c8b9b407702)
![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/6623611/8da9d7e4-1ba1-4269-8edc-862fc7841990)

**Comment by PatrikTrestik** [comment]
I'll fix it, but it will be little harder. I have to add version check not to break older fw.

@josefburger please share latest Modbus mapping. Doc or link. Thanks.

**Comment by josefburger** [comment]
I'm sorry, I forgot to attach
[EvCharger ModbusRTU V3.5.pdf](https://github.com/user-attachments/files/16011761/EvCharger.ModbusRTU.V3.5.pdf)

**Comment by josefburger** [comment]
Register `"reg":70` doesn't change anything at all, you know the new reg number for http api? I can't make it out.

**Comment by PatrikTrestik** [comment]
> Register `"reg":70` doesn't change anything at all, you know the new reg number for http api? I can't make it out.

There is no official document for API. All I have is reverse engineering from Android app. I have to check if there is new version and decompile again.

I use ModbusReg numbers only to keep reference to solax-modbus. Actual number have no meaning in this code. But I think that with change in modbus they also changed API.
Researching.

**Comment by PatrikTrestik** [comment]
If you have 3 phase changer, this setting has no meaning. Even SolaxCloud app is not showing it.

For 1-phase it is indicating which wire is changer connected on to correctly report to Inverter. It should work with API as is now.

**Comment by PatrikTrestik** [comment]
I decompiled latest SolaxCloud app and checked mapping. There is nothing significantly new on API.

I agree that Modbus reg id is different, but because it has no functional meaning here, I'll not change it.  

If you find it not working, please try to simulate correct function with SolaxCloud app and make screenshots. I can than try to find same in code.

Closing the bug, but feel free to reopen.

**Comment by josefburger** [comment]
> If you have 3 phase changer, this setting has no meaning. Even SolaxCloud app is not showing it.
Oh, I thought I could switch the charger from three to single phase. In that case, sorry for the unnecessary ticket.
