### ISSUE TITLE
Add Current_ChargeMAX

### ISSUE THREAD

**Issue by PatrikTrestik** [PatrikTrestik/homeassistant-solax-http#4]
As per @johny-mnemonic : 
Did you try to play with the Current_ChargeMAX?
I have seen it in the alfa version of your integration (now it's gone) and I see it in the app, where it is possible to set it to current between 6 and 16A when charger is set to Fast mode.

**Comment by matomatusov** [comment]
[PatrikTrestik](https://github.com/PatrikTrestik)

I am sending this picture

![Screenshot_20231201-143733](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/a5855d27-f2d2-46d6-8fc9-79aa29419677)

The user can set the max charging current for the EV-Charger based on actual need on the
control page by touching Current_ChargeMax. This function will only take effect in FAST
mode in Home scene. The range is 6 A to 32 A for 7 kW and 22 kW models, 6 A to 16 A for
11 kW models.

**Comment by matomatusov** [comment]
Just write to solax support. support update the wallbox remotely. The latest version is 1.12.
service.eu@solaxpower.com

**Comment by Xeudoron** [comment]
Hello,
and first of all, thank you Patrik for this amazing integration. I've just installed it next to the one from Wills106 and basic functions work like a charm (need to do more testing and maybe setup some automations based on actual spot prices).

Second, some time ago I've found this amazing place on the internet - https://app.box.com/s/3nvo7ic523fhojf8uuto105q9a8dgk9n/folder/227173376943, where you can download the 1.12 fw. (I'm still on 1.8 but will try soon). There are also other firmwares for many SolaX devices.

**Comment by PatrikTrestik** [comment]
> Just write to solax support. Support update the wallbox remotely. The latest version is 1.12. [service.eu@solaxpower.com](mailto:service.eu@solaxpower.com)

Thanks for advice. They updated it without problem to fw 1.12.

**Comment by PatrikTrestik** [comment]
Added in last version. Charge Current support was added somewhere between firmware version 1.08 and 1.12.
If you are on 1.08 or lower, it will not be there.

**Comment by matomatusov** [comment]
Hi,
it was added in 1.10 but it didn't work. It started working only on 1.12.
