### ISSUE TITLE
SolaX Inverter Battery Charge Upper SOC

### ISSUE THREAD

**Issue by Henry1-github** [PatrikTrestik/homeassistant-solax-http#40]
"SolaX Inverter Battery Charge Upper SOC" can't be set by the SolaX Modbus Integration. After a few seconds it always falls back to the value set in the SolaX cloud app.

**Comment by romankysely** [comment]
Yes, I agree this glitch too but I am afraid that you have to forwad there to another integration: https://github.com/wills106/homeassistant-solax-modbus/issues/1017
This integration is about EV Charge only.

**Comment by PatrikTrestik** [comment]
@Henry1-github please fill it in correct project as mentioned by Roman.
I'll look on it when I'm home. 

Closing this.
