### ISSUE TITLE
Solax Wallbox X3-EVC-11K(SXH) Charge Max Current

### ISSUE THREAD

**Issue by pdjoergb** [PatrikTrestik/homeassistant-solax-http#45]
Hi Patrik,

thanks for your integration, it works fine, values are updated each 15s. I can control several settings like e.g. Charger Use Mode.

Now I would like to automatically control the "Charge Max Current", but the parameter solax_api_max_charge_current_setting is not shown ("unknown") and could not be changed. Is this a problem with the integration, the (slightly) older firmware or because of older hardware?

Same question with solax_api_charge_phase...

Equipment:
- Solax X3-EVC-11k(SXH)
- Serial is C3110...
- Firmware 1.08
- WIFI-Firmware 3.004.11

Regards
  Joerg

**Comment by PatrikTrestik** [comment]
Hi.
Unfortunately I'll be out of home till 12.12. 
I'll look on solax_api_max_charge_current_setting but I need access to my hardware.

For solax_api_charge_phase I think it is for single phase EVC only. It sets where it is physically connected.
It could not control single phase charging for three phase EVC.

**Comment by PatrikTrestik** [comment]
> Hi. Unfortunately I'll be out of home till 12.12. I'll look on solax_api_max_charge_current_setting but I need access to my hardware.
> 
> For solax_api_charge_phase I think it is for single phase EVC only. It sets where it is physically connected. It could not control single phase charging for three phase EVC.

For charge phase see my reply here: https://github.com/wills106/homeassistant-solax-modbus/discussions/349#discussioncomment-11595822
