### ISSUE TITLE
setReg method timeouts on my wallbox

### ISSUE THREAD

**Issue by Bobris** [PatrikTrestik/homeassistant-solax-http#47]
Hello,

I don't know what I am doing wrong but getting realtimedata works:
{"SN":"SQ...","ver":"3.004.11","type":1,"Data":[2,3,23387,23295,23530,0,0,0,0,0,0,0,0,0,1382,0,113,65498,65481,16,65531,65535,0,0,21,0,2,15,0,0,0,0,0,5000,4994,5002,15128,2839,6156,3,0,0,0,0,0,0,0,0,1,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,15115,2839,6156,0,1,1,1,0,0,120,599,100,0,51],"Information":[11.000,1,"C31103J...",1,1.08,1.01,0.00,0.00,0.00,1],"OCPPServer":"","OCPPChargerId":""}

But then I tried to set mode with:
optType=setReg&pwd=SQ...&data={"num":1,"Data":[{"reg":2,"val":2}]}

It timeout, if I will currupt data json it closes connection, so I think I am doing request right.
But to be honest setting mode from SolaxCloud also does nothing. (Only way it works is with hardware button on wallbox).

Maybe I have some buggy version (It is older than 1 year).

Any ideas what could be wrong?

**Comment by Bobris** [comment]
Hi.

I just call it with curl. I just reverse-engineered your code. My wallbox is in "Green" mode and I want to switch it by that request to "Eco" mode. I also verified that value of that reg=2 before calling that setReg is 3 (Green), and val=2 should be "Eco". Of course I am very careful with calling requests on Wallbox, but all values matches so I tried it and wallbox itself works without change. I understand that it is not your problem, just if you don't see any obvious error in what I did. I am filing a complaint with my supplier, because it should work from SolaXCloud mobile application and it also does not change mode.
Thanks for your time.

**Comment by PatrikTrestik** [comment]
Hi. And reason why you run it by hand? Is integration not working?

I see that you have older version 1.08. There ware changes lately on SolaX side. But not touching Mode.

If it does not work in SolaXCloud app, start searching there and contact SolaX support. 
Ugrade Solax app and EVC firmware (SolaX support will do it on request).

**Comment by Bobris** [comment]
I just like to build my home automation all by myself. Thanks again.
