### ISSUE TITLE
X1-HAC-7P

### ISSUE THREAD

**Issue by Youre-a-Wizard** [PatrikTrestik/homeassistant-solax-http#52]
Hi Patrik, love your work mate. Similar to the X3-HAC-22P thread, I own a X1-HAC-7P. Is it possible to integrate the single phase X1-HAC-7P in this integration based off work done for the X3-HAC-22P?

See below 'curl' output:

{"SN":"XCQCxxxxx","ver":"002.00","type":3,"Data":[0,0,0,24855,0,0,0,0,0,0,0,0,0,0,0,0,0,65513,0,0,65535,0,0,0,22,25,0,0,0,0,0,0,0,4986,0,0,2309,3593,6156,6,0,0,0,0,0,0,0,0,1,0,0,0,0,0,49,1202,1000,0,44,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,65496,50,2,0,0,0,0],"Information":[7.000,3,"502071110R02CP",2,1.28,1.01,0.00,0.00,0.00,1,1,0,5],"OCPPServer":"","OCPPChargerId":"","QRContent":""}

Cheers

**Comment by PatrikTrestik** [comment]
Great, thanks for joiniing club 😄 

I'll add type detection in next version.

Please follow #42. General progress will be shared there.
You should open new issue for sensors/functions you are missing. Best is to show screenshot from mobile app as reference.

**Comment by PatrikTrestik** [comment]
New typed added in v1.3.2
