### ISSUE TITLE
The correct version is not displayed

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#55]
Hi, 
I noticed that the correct version 1.33 is not showing in the integration.

![Solax EV charger version](https://github.com/user-attachments/assets/1fbcfead-765b-4665-91d5-f637e3a955ce)

**Comment by PatrikTrestik** [comment]
Thanks for spotting.
Probably my mistake while manual editing.

Will fix soon.
