### ISSUE TITLE
Charge current  (range)

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#6]
Hi,
I think the range is wrong.
The range is 6 A to 32 A for 7 kW and 22 kW models, 6 A to 16 A for
11 kW models.

![charge current](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/1c55d9d5-dd0e-47d8-97bb-47e8ff605beb)

**Comment by PatrikTrestik** [comment]
You are right. I'll add limits dependent on version in next iteration.

**Comment by PatrikTrestik** [comment]
Fixed.

**Comment by matomatusov** [comment]
Hi,
thanks, good work.
