### ISSUE TITLE
unknown values

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#7]
Hi,
after the last update, all values became unknown.
you don't know what could be the problem?

The bug returned **Charge current (range)** 

![image](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/808c5cf5-ef37-47ab-96b7-b08bf3bddb30)

![current](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/c0059e76-77aa-4970-9255-bdd5e7dbef07)

**Comment by PatrikTrestik** [comment]
Please post logs, if there are any errors.
I'll check code for Charge current, it was last addition.

**Comment by matomatusov** [comment]
Tato chyba pochází z vlastní integrace.

Logger: homeassistant
Source: custom_components/solax_http/plugin_solax_ev_charger.py:784
Integration: SolaX Inverter Local API (documentation)
First occurred: 22:36:48 (85 occurrences)
Last logged: 22:55:37

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/config/custom_components/solax_http/sensor.py", line 76, in _handle_coordinator_update
    self._value = self.coordinator.get_data(self.entity_description)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_http/coordinator.py", line 64, in get_data
    return self.plugin.map_data(descr, self.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_http/plugin_solax_ev_charger.py", line 784, in map_data
    return_value=datetime.datetime(2000+year,month,day,hour,minute,second).astimezone()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: month must be in 1..12

**Comment by PatrikTrestik** [comment]
Thanks for logs. It looks like your charger reports different date format. I added log to see what happend.

**Comment by PatrikTrestik** [comment]
Please install latest version and search log for warning 'invalid date data'. It helps me a lot.

**Comment by matomatusov** [comment]
and where can i find warning 'invalid date data'?

thanks

**Comment by matomatusov** [comment]
After uploading the new version, the data is displayed.

**Comment by PatrikTrestik** [comment]
> and where can I find warning 'invalid date data'?
> 
> thanks

Open Settings >System>Logs and read full logs. There you can search for it.
I fixed error only by skipping so I want to know what was value causing error.

**Comment by matomatusov** [comment]
Tato chyba pochází z vlastní integrace.

Logger: custom_components.solax_http.plugin_solax_ev_charger
Source: custom_components/solax_http/plugin_solax_ev_charger.py:787
Integration: SolaX Inverter Local API (documentation)
First occurred: 23:18:45 (36 occurrences)
Last logged: 23:26:39

invalid date data 840,830,820

**Comment by PatrikTrestik** [comment]
> Tato chyba pochází z vlastní integrace.
> 
> Logger: custom_components.solax_http.plugin_solax_ev_charger Source: custom_components/solax_http/plugin_solax_ev_charger.py:787 Integration: SolaX Inverter Local API (documentation) First occurred: 23:18:45 (36 occurrences) Last logged: 23:26:39
> 
> invalid date data 840,830,820

Thanks.

Do you have car connected? When you last used charger?
What is firmware version of charger (should be displayed by integration)?

**Comment by matomatusov** [comment]
firmware version of charger 1.12.
I used the charger yesterday.

**Comment by PatrikTrestik** [comment]
I found issue. For me after Charger restart (power down) it will reset values.
I'll fix Last charge time to work correctly with it. 
Please confirm that next time you connect car, it will show "Charge start time" correctly. Thanks.

**Comment by PatrikTrestik** [comment]
Fixed in last version.
