### ISSUE TITLE
Eco Mode 6A & 10A

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#8]
Hi,
Eco mode it has two levels.
Level 1 - 6A
Level 2 - 10A

Green mode is OK.

Thanks

![eco mode](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/9bd6e4bb-cae1-4688-a9eb-0c29fa137293)

**Comment by PatrikTrestik** [comment]
I copied it from Modbus document.
We both have 11kW charger. I expect that other values are for 22kW. In next version I'll split entity by charger power.
Simple change, but no time to do it now.

**Comment by PatrikTrestik** [comment]
Fixed.
