### ISSUE TITLE
Question: addition smart boost

### ISSUE THREAD

**Issue by matomatusov** [PatrikTrestik/homeassistant-solax-http#9]
Hi,
wouldn't it be possible to add a smart boost?
Or a timer as well?

Thanks

![Screenshot_20231217-154510](https://github.com/PatrikTrestik/homeassistant-solax-http/assets/129114957/58cb3681-932d-4e56-b77a-8b6d508f084d)

**Comment by PatrikTrestik** [comment]
Yes, I know where it is. I only didn't have time to test. Expect it first week in Jan 2024 😄

**Comment by PatrikTrestik** [comment]
I quickly added it in last version. Please be aware that I did not tested it a lot. Please check if all works and expect errors.

**Comment by matomatusov** [comment]
Hi,
the entity  Grid Power Total has stopped being displayed.
Entity Charge start time - unknown

**Comment by PatrikTrestik** [comment]
Sorry for breaking change. I have to start writing release notes.

This sensor was renamed. 
During investigation of smart functions I found that it is "Available energy from PV" and not Grid total.

You will find it under new name.

If there is PV power it shows positive numbers while there is surplus (grid export+battery charge).

**Comment by johny-mnemonic** [comment]
I can confirm that setting the boost related stuff from HA appears configured correctly in the Solax app. 

My trouble is I don't understand how it works. Maybe it is another thing that is broken in the charger as setting for example Smart Boost with the amount to charge and the end of charging and switching boost mode to Smart Boost does nothing for me. This is obviously not the issue of the integration.

**Comment by PatrikTrestik** [comment]
Closing as solved. Smart boost sensors work on integration side. We have to test if and how it works in SolaX EVC.
